# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='order',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
