# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20161214_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
