# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_entry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='map_url',
            field=models.CharField(max_length=4000),
        ),
    ]
