# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20161214_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-entry_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='book_url',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='site_url',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='song_url',
            field=models.CharField(max_length=3000),
        ),
    ]
