# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20161214_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='book_url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='map_url',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo_url',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='site_url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='song_url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
