# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20161214_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='desc',
            new_name='long_text',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='title',
            new_name='short_text',
        ),
    ]
